make: 
	g++ -c f3point.cpp
	g++ -c collision_source.cpp
	g++ -c source.cpp
	g++ -c polygon.cpp
	g++ -c gameobject.cpp
	g++ -c lend.cpp
	g++ -c food.cpp
	g++ -c rock.cpp
	g++ -o  source source.o f3point.o collision_source.o polygon.o gameobject.o lend.o food.o rock.o -lglut -lGLU -lGL -lm